### ISSUE TITLE
`autoplayForcedMode` doesn't seem to work correctly

### ISSUE THREAD

**Issue by bradenhilton** [Invertex/Gfycat-AutoHD#6]
First I would just like to quickly say that I find this script incredibly useful.

I'm running v1.81 of the script with Violentmonkey on Firefox 96 and the `autoplayForcedMode` flag does not seem to work. I can set it to `"on"` or `"off"` with no change.

Some questions/critiques if I may:

- I noticed that you use GM get/set value for the `audioEnabled` flag - Couldn't you also use this for `autoplayForcedMode` to prevent it being reset by a script update? Toggling the switch could update the value.
- You check if `autoplayForcedMode` is not `null` before running `setAutoplayState`, then check if it's `null` again within `setAutoplayState` - Is there a particular reason for this? Surely `setAutoplayState` is only run if `autoplayForcedMode` is not `null`?

It works as expected for me with the following change, though I'm not entirely sure why:

```diff
function setAutoplayState(autoplayButton)
{
-    let forcedMode = (autoplayForcedMode || autoplayForcedMode == "on") ? true : false;
+    let forcedMode = autoplayForcedMode == "on" ? true : false;

	if(autoplayButton != null && autoplayButton.checked != forcedMode)
	{
        autoplayButton.click();
	}
};
```

I think you could also swap `let` with `const`, given that the value does not change. You could also make the comparisons more strict:

```diff
function setAutoplayState(autoplayButton)
{
-    let forcedMode = autoplayForcedMode == "on" ? true : false;
+    const forcedMode = autoplayForcedMode === "on" ? true : false;

-	if(autoplayButton != null && autoplayButton.checked != forcedMode)
+	if(autoplayButton !== null && autoplayButton.checked !== forcedMode)
	{
        autoplayButton.click();
	}
};
```

What do you think? Are my proposed changes good enough? Is using GM get/set value a possibility?

If you're happy with my proposed changes, I just wanted to say that I don't really care about any kind of credit, so feel free to make the changes yourself if you want.

**Comment by Invertex** [comment]
The first change you made there was like that just as a safety mechanism in case someone set the variable to be `= true;`  instead of `= "on"`. 

I didn't implement the GM Get/Set stuff until many versions after I had the `autoplayForcedMode` stuff, so it's simply that I haven't gotten around to implementing that using the interface.

`const` vs `let` isn't that important there. Using a local `const` primarily helps avoid mistakes of setting a variable again when you intended for it to be immutable, but it's only a few lines of code in that function so such a thing wouldn't really happen. But yes setting it `const` should be fine and is general best practice when you're sure of the intent.

It's better to use `!= null` when dealing with objects so you can handle both `undefined` or `null` state comparison in one imo. `!==` would return false if `autoplayButton` was `undefined` instead of `null`.

As for the `.checked` part, it's not a scenario where it would be an issue so either way is fine.
